data_template_path: "/pscratch/sd/m/maccrann/cmb/act_dr6/sims_v4/gaussian_sims_v4_mask60sk/data_alm_${freq}_split${split}.fits"
sim_template_path: "/pscratch/sd/m/maccrann/cmb/act_dr6/sims_v4/gaussian_sims_v4_mask60sk/${freq}_isim${actseed}.fits"
mask: /global/cfs/projectdirs/act/data/maccrann/dr6/act_mask_20220316_GAL060_rms_60.00sk.fits
K_lmin: 3000
mlmax: 4000
K_lmax: 4000
do_auto: True
do_rdn0: False
nsim_rdn0: 32
get_sims_from_cls: False
do_lh: False
do_psh: False
nsim_meanfield: 64
ksz_theory_alm_file: "../tests/alms_4e3_2048_50_50_ksz.fits"