data_template_path: "/pscratch/sd/m/maccrann/cmb/act_dr6/ilc_cldata_smooth-301-2_v4_lmax6000_60skmask/${freq}_split${split}.fits"
sim_template_path: "/pscratch/sd/m/maccrann/cmb/act_dr6/ilc_cldata_smooth-301-2_v4_lmax6000_60skmask/gaussian_sims/${freq}_isim${actseed}.fits"
mask: /global/cfs/projectdirs/act/data/maccrann/dr6/act_mask_20220316_GAL060_rms_60.00sk.fits
K_lmin: 3000
mlmax: 6000
K_lmax: 6000
do_auto: True
do_rdn0: False
nsim_rdn0: 64
get_sims_from_cls: False
do_lh: False
do_psh: True
skip_qe: True
nsim_meanfield: 64
ksz_theory_alm_file: "../tests/alms_4e3_2048_50_50_ksz.fits"